development:                            #setting the database for the development environment
  adapter: mysql2
  encoding: utf8
  database: wisamquais
  pool: 5
  username: wisamquais
  password:
  timeout: 5000
  # socket: /var/run/mysqld/mysqld.sock