development:                            #setting the database for the development environment
  adapter: mysql2
  encoding: utf8
  database: pda_development
  pool: 5
  username: root
  password: '1234'
  timeout: 5000
  socket: /var/run/mysqld/mysqld.sock
