# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce38e3b3e47e8a97e40be33deeb32d194349424b738898c4dab09b67d15880333aa2cbb3dfcedec77936bd4d5190eabe44ade77360d0941553f8424f0bd87fce

test:
  secret_key_base: f5a8f1cd30234f7280d7e0126ecb996750702ab6e705a96e8b4b6a67cdaea14eef8dcffa61ce93d7f1bb3c16bcd5c826b7fc3b8c23d4d29ee50b7f24ceae5c21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
